server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: http://localhost:8084/
          predicates:
            - Path=/service1/**
        - id: service2
          uri: http://localhost:8085/
          predicates:
            - Path=/service2/**
        - id: service3
          uri: http://localhost:8086/
          predicates:
            - Path=/service3/**
        - id: DZ_sem6
          uri: http://localhost:8087/
          predicates:
            - Path=/note_service/**
